use super::FFMPEG_REQUIRED_VERSION;
use super::contracts::{EngineMode, ToolDef};

pub(super) const COMPATIBLE_VERSION: &str = "compatible";
pub(super) const APP_VERSION: &str = env!("CARGO_PKG_VERSION");

pub(super) const TOOLS: &[ToolDef] = &[
    ToolDef {
        id: "ffmpeg",
        label: "FFmpeg",
        role: "Audio / vidéo principal",
        description: "Conversion audio, conversion vidéo et extraction audio depuis vidéo.",
        mode: EngineMode::Base,
        commands: &["ffmpeg"],
        engine_kind: "portable",
        managed: true,
        expected_version: FFMPEG_REQUIRED_VERSION,
        estimated_size: "80 à 180 Mo",
        categories: &["audio", "video"],
        conversions: &["audio", "video", "video->audio"],
        capabilities: &["audio", "video"],
        action_label: "Réparer",
        dependencies: &[],
    },
    ToolDef {
        id: "ffprobe",
        label: "ffprobe",
        role: "Analyse audio / vidéo",
        description: "Inspection réelle des fichiers média avant conversion.",
        mode: EngineMode::Base,
        commands: &["ffprobe"],
        engine_kind: "portable",
        managed: true,
        expected_version: FFMPEG_REQUIRED_VERSION,
        estimated_size: "Inclus avec FFmpeg",
        categories: &["audio", "video"],
        conversions: &["analyse média"],
        capabilities: &["media-analysis"],
        action_label: "Réparer",
        dependencies: &["ffmpeg"],
    },
    ToolDef {
        id: "rust-image",
        label: "Moteur images intégré",
        role: "Images courantes",
        description: "PNG, JPG/JPEG, WEBP, TIFF, BMP et ICO quand supporté.",
        mode: EngineMode::Base,
        commands: &[],
        engine_kind: "integrated",
        managed: true,
        expected_version: APP_VERSION,
        estimated_size: "Inclus",
        categories: &["images"],
        conversions: &["images raster courantes"],
        capabilities: &["images"],
        action_label: "Intégré",
        dependencies: &[],
    },
    ToolDef {
        id: "resvg",
        label: "resvg",
        role: "SVG vers image raster",
        description: "Rasterisation SVG locale. Ne génère pas de faux SVG depuis une image raster.",
        mode: EngineMode::Base,
        commands: &[],
        engine_kind: "integrated",
        managed: true,
        expected_version: APP_VERSION,
        estimated_size: "Inclus",
        categories: &["images"],
        conversions: &["svg->png", "svg->jpg", "svg->webp", "svg->tiff"],
        capabilities: &["svg-raster"],
        action_label: "Intégré",
        dependencies: &["rust-image"],
    },
    ToolDef {
        id: "rust-text",
        label: "Moteur texte intégré",
        role: "Documents simples et données",
        description: "TXT, Markdown simple, HTML basique, CSV, JSON, XML et génération document texte basique.",
        mode: EngineMode::Base,
        commands: &[],
        engine_kind: "integrated",
        managed: true,
        expected_version: APP_VERSION,
        estimated_size: "Inclus",
        categories: &["documents"],
        conversions: &["texte simple", "csv/json/xml"],
        capabilities: &["documents", "structured-data"],
        action_label: "Intégré",
        dependencies: &[],
    },
    ToolDef {
        id: "pdf-extract",
        label: "pdf-extract",
        role: "Fallback PDF texte simple",
        description: "Extraction PDF texte simple en Base légère.",
        mode: EngineMode::Base,
        commands: &[],
        engine_kind: "integrated",
        managed: true,
        expected_version: APP_VERSION,
        estimated_size: "Inclus",
        categories: &["documents"],
        conversions: &["pdf->texte simple"],
        capabilities: &["pdf-text-fallback"],
        action_label: "Intégré",
        dependencies: &["rust-text"],
    },
    ToolDef {
        id: "pdfium",
        label: "PDFium",
        role: "Rendu PDF haute qualité",
        description: "Rendu de pages PDF vers images.",
        mode: EngineMode::Advanced,
        commands: &["pdfium-render"],
        engine_kind: "portable",
        managed: true,
        expected_version: COMPATIBLE_VERSION,
        estimated_size: "Embarqué avec l'application",
        categories: &["documents", "images"],
        conversions: &["pdf->image"],
        capabilities: &["pdf-render"],
        action_label: "Intégré",
        dependencies: &[],
    },
    ToolDef {
        id: "libreoffice",
        label: "LibreOffice headless",
        role: "Documents fidèles",
        description: "Conversions Office/PDF plus fidèles en mode headless.",
        mode: EngineMode::Advanced,
        commands: &["soffice"],
        engine_kind: "portable",
        managed: true,
        expected_version: COMPATIBLE_VERSION,
        estimated_size: "Embarqué avec l'application",
        categories: &["documents"],
        conversions: &["docx", "odt", "rtf", "html", "pdf"],
        capabilities: &["office"],
        action_label: "Intégré",
        dependencies: &[],
    },
    ToolDef {
        id: "pandoc",
        label: "Pandoc",
        role: "Documents Markdown/HTML/ePub",
        description: "Conversions structurées entre Markdown, HTML, ePub et DOCX.",
        mode: EngineMode::Advanced,
        commands: &["pandoc"],
        engine_kind: "portable",
        managed: true,
        expected_version: COMPATIBLE_VERSION,
        estimated_size: "Embarqué avec l'application",
        categories: &["documents"],
        conversions: &["markdown", "html", "epub", "docx"],
        capabilities: &["document-structure"],
        action_label: "Intégré",
        dependencies: &[],
    },
    ToolDef {
        id: "libvips",
        label: "libvips",
        role: "Images avancées",
        description: "Conversions raster avancées via moteur portable.",
        mode: EngineMode::Advanced,
        commands: &["vips"],
        engine_kind: "portable",
        managed: true,
        expected_version: COMPATIBLE_VERSION,
        estimated_size: "Embarqué avec l'application",
        categories: &["images"],
        conversions: &["png", "jpg", "webp", "tiff"],
        capabilities: &["advanced-images"],
        action_label: "Intégré",
        dependencies: &[],
    },
];

pub fn tool_label(id: &str) -> &'static str {
    match id {
        "non-integrated" | "external" => "Conversion non intégrée",
        _ => TOOLS
            .iter()
            .find(|tool| tool.id == id)
            .map(|tool| tool.label)
            .unwrap_or("Conversion non intégrée"),
    }
}
